"use client";
import { useState } from "react";

const sections = [
  {
    id: "interpretation",
    title: "Interpretation & Definitions",
    content: [
      {
        subtitle: "Interpretation",
        text: `The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
      },
      {
        subtitle: "Definitions",
        text: null,
        list: [
          { term: "Account", def: "A unique account created for You to access our Service or parts of our Service." },
          { term: "Affiliate", def: `An entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.` },
          { term: "Application", def: "The software program provided by the Company downloaded by You on any electronic device, named Crop2X." },
          { term: "Company", def: `Referred to as either "the Company", "We", "Us" or "Our" in this Agreement — refers to Crop2X Pvt. Ltd., Suite # A-203, Tower A, 2nd Floor, Blossom Trade Centre, Block-1, Gulistan e Jauhar, University Road, Karachi.` },
          { term: "Country", def: "Pakistan" },
          { term: "Device", def: "Any device that can access the Service such as a computer, a cellphone, or a digital tablet." },
          { term: "Personal Data", def: "Any information that relates to an identified or identifiable individual." },
          { term: "Service", def: "Refers to the Application." },
          { term: "Service Provider", def: "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used." },
          { term: "Usage Data", def: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
          { term: "You", def: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
        ],
      },
    ],
  },
  {
    id: "collecting",
    title: "Collecting & Using Your Personal Data",
    content: [
      {
        subtitle: "Types of Data Collected",
        text: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
        list: [
          { term: "First name and last name" },
          { term: "Phone number" },
          { term: "Address, State, Province, ZIP/Postal code, City" },
          { term: "Usage Data" },
        ],
      },
      {
        subtitle: "Use of Your Personal Data",
        text: "The Company may use Personal Data for the following purposes:",
        list: [
          { term: "To provide and maintain our Service", def: "including monitoring the usage of our Service." },
          { term: "To manage Your Account", def: "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user." },
          { term: "For the performance of a contract", def: "the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service." },
          { term: "To contact You", def: "by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation." },
          { term: "To provide You with news and special offers", def: "and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information." },
          { term: "To manage Your requests", def: "to attend and manage Your requests to Us." },
          { term: "For business transfers", def: "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets." },
          { term: "For other purposes", def: "such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your experience." },
        ],
      },
      {
        subtitle: "Sharing Your Personal Information",
        text: "We may share Your personal information in the following situations:",
        list: [
          { term: "With Service Providers", def: "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You." },
          { term: "For business transfers", def: "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of Our business to another company." },
          { term: "With Affiliates", def: "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy." },
          { term: "With business partners", def: "We may share Your information with Our business partners to offer You certain products, services, or promotions." },
          { term: "With other users", def: "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside." },
          { term: "With Your consent", def: "We may disclose Your personal information for any other purpose with Your consent." },
        ],
      },
    ],
  },
  {
    id: "retention",
    title: "Retention of Your Personal Data",
    content: [
      {
        text: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\nThe Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.`,
      },
    ],
  },
  {
    id: "transfer",
    title: "Transfer of Your Personal Data",
    content: [
      {
        text: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.\n\nYour consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n\nThe Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.`,
      },
    ],
  },
  {
    id: "disclosure",
    title: "Disclosure of Your Personal Data",
    content: [
      {
        subtitle: "Business Transaction",
        text: "If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
      },
      {
        subtitle: "Law Enforcement",
        text: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
      },
      {
        subtitle: "Other Legal Requirements",
        text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
        list: [
          { term: "Comply with a legal obligation" },
          { term: "Protect and defend the rights or property of the Company" },
          { term: "Prevent or investigate possible wrongdoing in connection with the Service" },
          { term: "Protect the personal safety of users of the Service or the public" },
          { term: "Protect against legal liability" },
        ],
      },
    ],
  },
  {
    id: "security",
    title: "Security of Your Personal Data",
    content: [
      {
        text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      },
    ],
  },
  {
    id: "links",
    title: "Links to Other Websites",
    content: [
      {
        text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.\n\nWe have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.",
      },
    ],
  },
  {
    id: "changes",
    title: "Changes to This Privacy Policy",
    content: [
      {
        text: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\nWe will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last Updated" date at the top of this Privacy Policy.\n\nYou are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
      },
    ],
  },
];

export default function PrivacyPolicyPage() {
  const [activeSection, setActiveSection] = useState(null);

  return (
    <>
      {/* ── Hero ── */}
      <section className="relative py-24 md:py-32 overflow-hidden">
        <div className="absolute inset-0">
          <img
            src="/assets/pricing.png"
            alt="Privacy Policy"
            className="w-full h-full object-cover scale-105"
          />
        </div>
        <div className="absolute inset-0 bg-gradient-to-br from-black/80 via-black/60 to-black/80" />
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2260%22%20height%3D%2260%22%20viewBox%3D%220%200%2060%2060%22%20xmlns%3D%22http://www.w3.org/2000/svg%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cg%20fill%3D%22%23ffffff%22%20fill-opacity%3D%220.05%22%3E%3Cpath%20d%3D%22M36%2034v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6%2034v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6%204V0H4v4H0v2h4v4h2V6h4V4H6z%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-30" />
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center text-white">
          <span className="inline-block bg-green-600/30 border border-green-500/40 text-green-300 text-sm font-medium px-4 py-1.5 rounded-full mb-6 tracking-wide uppercase">
            Legal
          </span>
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-6">
            Privacy Policy
          </h1>
          <p className="text-lg md:text-xl text-green-100 max-w-2xl mx-auto">
            How Crop2X collects, uses, and protects your personal information.
          </p>
          <p className="mt-4 text-sm text-gray-400">Last Updated: 2025</p>
        </div>
      </section>

      {/* ── Intro Banner ── */}
      <section className="bg-green-600 py-6">
        <div className="max-w-5xl mx-auto px-6 text-white text-center text-sm md:text-base">
          This Privacy Policy describes our policies and procedures on the collection, use and disclosure of Your information when you use the Service and tells you about your privacy rights and how the law protects You.
        </div>
      </section>

      {/* ── Main Content ── */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6 flex gap-12">

          {/* Sidebar TOC — sticky */}
          <aside className="hidden lg:block w-64 shrink-0">
            <div className="sticky top-8">
              <p className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-4">
                Contents
              </p>
              <nav className="space-y-1">
                {sections.map((s) => (
                  <a
                    key={s.id}
                    href={`#${s.id}`}
                    className="block text-sm text-gray-500 hover:text-green-600 hover:translate-x-1 transition-all duration-200 py-1.5 border-l-2 border-transparent hover:border-green-500 pl-3"
                  >
                    {s.title}
                  </a>
                ))}
                <a
                  href="#contact"
                  className="block text-sm text-gray-500 hover:text-green-600 hover:translate-x-1 transition-all duration-200 py-1.5 border-l-2 border-transparent hover:border-green-500 pl-3"
                >
                  Contact Us
                </a>
              </nav>
            </div>
          </aside>

          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="space-y-12">
              {sections.map((section) => (
                <div key={section.id} id={section.id} className="scroll-mt-8">
                  {/* Section Header */}
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-1 h-8 bg-green-500 rounded-full" />
                    <h2 className="text-2xl font-bold text-gray-900">
                      {section.title}
                    </h2>
                  </div>

                  {/* Section Body */}
                  <div className="space-y-6 pl-4">
                    {section.content.map((block, bi) => (
                      <div key={bi}>
                        {block.subtitle && (
                          <h3 className="text-lg font-semibold text-gray-800 mb-3">
                            {block.subtitle}
                          </h3>
                        )}
                        {block.text && (
                          <p className="text-gray-600 leading-relaxed whitespace-pre-line mb-3">
                            {block.text}
                          </p>
                        )}
                        {block.list && (
                          <ul className="space-y-3 mt-3">
                            {block.list.map((item, li) => (
                              <li key={li} className="flex gap-3">
                                <span className="mt-1.5 w-2 h-2 rounded-full bg-green-500 shrink-0" />
                                <span className="text-gray-600 text-sm leading-relaxed">
                                  {item.term && item.def ? (
                                    <>
                                      <span className="font-semibold text-gray-800">
                                        {item.term}
                                      </span>{" "}
                                      — {item.def}
                                    </>
                                  ) : (
                                    item.term
                                  )}
                                </span>
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>

                  {/* Divider */}
                  <div className="mt-10 border-b border-gray-100" />
                </div>
              ))}

              {/* Contact Section */}
              <div id="contact" className="scroll-mt-8">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-1 h-8 bg-green-500 rounded-full" />
                  <h2 className="text-2xl font-bold text-gray-900">Contact Us</h2>
                </div>
                <p className="text-gray-600 mb-6 pl-4">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <div className="pl-4 grid sm:grid-cols-2 gap-4">
                  <a
                    href="mailto:info@Crop2x.com"
                    className="flex items-center gap-4 p-5 rounded-xl border border-gray-200 hover:border-green-400 hover:shadow-md transition-all duration-200 group"
                  >
                    <div className="w-10 h-10 rounded-lg bg-green-100 flex items-center justify-center group-hover:bg-green-600 transition-colors">
                      <svg className="w-5 h-5 text-green-600 group-hover:text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 uppercase tracking-wide mb-0.5">Email</p>
                      <p className="text-sm font-medium text-gray-800 group-hover:text-green-600 transition-colors">info@Crop2x.com</p>
                    </div>
                  </a>
                  <div className="flex items-center gap-4 p-5 rounded-xl border border-gray-200">
                    <div className="w-10 h-10 rounded-lg bg-green-100 flex items-center justify-center">
                      <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      </svg>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 uppercase tracking-wide mb-0.5">Phone</p>
                      <p className="text-sm font-medium text-gray-800">+92 21 37229763</p>
                      <p className="text-sm font-medium text-gray-800">+92 346 7666791</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}